### ISSUE TITLE
Mod works perfectly in Snowy biomes-- but fails to work with Serene Season "winter" in non-snowy biomes. Will compensate for your time!

### ISSUE THREAD

**Issue by ghost** [CrazyCrafter-DoctorTee/SnowAccumulation#7]
### Serene Seasons causes Snow in non-snowy biomes during "Winter" days.

With the mod Serene Seasons installed, snow layers can appear during "Winter" in biomes that normally don't get snow, such as regular forests and taiga. It's a really wonderful mod, and seeing snow come and go, throughout your world regardless of the biome type (snowy or not), with the turning of the seasons is **amazing**. Serene Seasons is one of the most popular 1.12.2. mods out there.

### **However, Snow Accumulation doesn't appear to accumulate in _any_ "non-originally-winter" biomes, even when it's "Winter Season", even when there is snow covering the ground during a snowstorm.**

![image](https://user-images.githubusercontent.com/71896090/135066253-3aad550d-63e2-4648-9d57-b1584c68b93f.png)

*In this image, you can see a "Snowy Tundra" biome accumulating snow during the winter perfectly.*

![image](https://user-images.githubusercontent.com/71896090/135066360-7db356ac-23fe-4833-92e9-9b3744a52afc.png)

*However, here you can see an adjacent "Taiga" biome, which gets rain the rest of the seasons except snow during the winter, is NOT accumulating more than one layer of snow despite the snowfall weather.*

---

### So, what do we do?

Instead of limiting snowfall by biome (biomeType?) like it is now, could you allow for snowfall to accumulate in _any_ biome, regardless of the biome type, as long as there is currently snowfall?

Please?

I'm willing to compensate you (via Paypal or whatever) for your time, as this mod is incredible and I'd love to include it in my upcoming modpack, [Finecraft](https://github.com/roccscout/Finecraft/wiki).

**Comment by CrazyCrafter-DoctorTee** [comment]
It looks like Serene Seasons does its own thing to set the block temperature, but provides an API so I'll try and look into it this weekend if I have time

**Comment by ghost** [comment]
Thank you -- that would be awesome!

**Comment by CrazyCrafter-DoctorTee** [comment]
1.12 forge is no longer supported, and I can't get the files to properly develop/build the mod (see https://github.com/MinecraftForge/ForgeGradle/issues/773 ) so I can't update the 1.12 version of Snow Accumulation

**Comment by ghost** [comment]
What do you mean forge 1.12.2 is no longer supported? I'm currently working with multiple mod authors who are working with 1.12.2.

**Comment by ghost** [comment]
Any update to this? I'm not sure what you mean forge is not supporting 1.12.2. I'm still working with more than 10 mod authors who are producing 1.12.2 mods all the time.

**Comment by CrazyCrafter-DoctorTee** [comment]
As seen in the github issue linked in my previous comment, part of the tooling required to write/build forge mods on 1.12.2 is no longer supported:
> despite 1.12 being out of support

If you know someone else who is able to build forge mods for 1.12, this mod's license would allow them to create their own patched version and distribute it.
